### ISSUE TITLE
Episode 2: Use of masks scene Lab - air conditioning - (CUT Lab)

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Proxymix#108]
Site: **UDG/CUT** (lab) howeber we have also room 104? What do we do with this?
1 Episode showing how the virus spread here.

Density Scenario: people are place with a distance of **2 meter** (if we have the real desk that could be possible to run it)

Code to run (and edit) in ````StoryTelling.gaml`````

``````
experiment Episode2 type: gui parent: Coronaizer{
	parameter 'fileName:' var: useCase category: 'file' <- "UDG/CUT/lab";
	parameter 'distance people:' var: distance_people category:'Visualization' min:0.0 max:5.0#m <- 2.0#m;
	parameter "Density Scenario" var: density_scenario category:'Initialization'  <- "num_people_room" among: ["data", "distance", "num_people_building", "num_people_room"];
	parameter 'People per Building (only working if density_scenario is num_people_building):' var: num_people_per_room category:'Initialization' min:0 max:100 <- 50;
}
``````

This is how it look so far 
<img width="850" alt="Screenshot 2020-08-24 at 12 35 15" src="https://user-images.githubusercontent.com/3928502/91035068-4a5ca800-e606-11ea-8ce6-5406a15eaba8.png">

TODO: CAN WE HAVE THE REAL DESK LAYOUT HERE?

**Comment by LAAP** [comment]
Hi @agrignard 

No idea about which room is best. @gamalielpalomo , @milkmonica , any answer? 

In the other side some small clarifications:

**2 sub episode:** 

_Pre-COVID19_ = No Mask (big sprawl) and 
_COVID19_ = mask (lower sprawl)

Density Scenarios:

_Pre-COVID19_ = 10 students per Lab
_COVID19_ = people are place with a distance of **2 meter** (if we have the real desk that could be possible to run it)

The rest as you have it below

**Comment by agrignard** [comment]
You have 4 sub episode here? Or is it a mistake form a copy/paste?

**Comment by LAAP** [comment]
@agrignard ,
There are 2 sub-episoids,  but we always show 2 things per episoid: the use **NO use of masks** with **pre COVID density** and, the **Use of Masks** with a new **COVID density**. Does it makes sense?

**Comment by LAAP** [comment]
In all the episodes we show "pre-COVID" Scenario, no masks, no nothing VS "COVID" scenario, Masks, low density, ventilation, distancing, etc. So, we show with and without masks in all the episodes.

Yes, in the "COVID" scenario, everyone (or at least 90% of people) will be wearing masks, so infection do not spreads

**Comment by agrignard** [comment]
I lost a bit inspiration here.

hwo do we want the clear difference betwsen the 2 episode? Just by playin with the number of infection?

**Comment by agrignard** [comment]
Firt attempt work in progress

Natural ventilation: lots of droplets and far 
AC: fewer droplet and close

WIP 
<img width="1578" alt="Screenshot 2020-09-01 at 15 35 46" src="https://user-images.githubusercontent.com/3928502/91858205-2aae2b00-ec69-11ea-9c52-f6c818a4b8bc.png">

**Comment by agrignard** [comment]
@gamalielpalomo and @milkmonica now that most of the feature are finally here and all the dxf are all ready  can you start to propose some content for this Episode? Let me know if you have any trouble to produce video with GAMA

**Comment by LAAP** [comment]
@agrignard ,

Same than in episode 1, @gamalielpalomo and @milkmonica should give us the specific "**details of the UDG protocols for LABs**" so we can adapt the simulation to UDG challenges. 

In here, I really like the idea of comparison of natural ventilation with AC. **However, we should see the meaning of it now that COVID is Airborne and not only Droplet based** Air droplets maybe not very affected by AC or ventilation, but aerosols yes:

_"There is little evidence that ventilation directly reduces the risk of disease transmission, but many studies suggest that insufficient ventilation increases disease transmission. A number of studies have looked at the possible transmission routes of diseases, but few have looked at the direct impact of ventilation on disease transmission." (https://www.ncbi.nlm.nih.gov/books/NBK143278/)_

_"Increasing ventilation rate can effectively reduce the risk of long-range airborne transmission, while it may be of little useful in preventing the droplet-borne transmission. To maintain the airflow direction from clean cubicles to dirty cubicles is an effective way to prevent the cross infection between cubicles, which is widely used in hospital isolation rooms." (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6072925/)_

In that sense, I am not sure about your simplification. My interpretation is: 

- **Natural ventilation:** lots of droplets and far  =  **BUT MORE air renovation, so that affects to the sprawl of the virus by aerosols = maybe "infectious load from droplets dissolves a bit or not but" but with Natural Air renewals every minute by the window I think that aerosols dissipate and "infectious load dissolves a bit"** isn't it?

- **AC:** fewer droplet and close = If air renovations is very little (traditional AC usually works with re-circulation of air and maybe 10% of new air by renovation) and no HEPA filters... then, This can mean that AC is not helping and it is increasing the "infectious load". Please read the following article: https://english.elpais.com/spanish_news/2020-06-17/an-analysis-of-three-covid-19-outbreaks-how-they-happened-and-how-they-can-be-avoided.html

**Comment by agrignard** [comment]
Update on th 09/09/2020

This is what we haev so far integrating all the recent changes made to show the impact of natural ventilation vs AC
Scenario A
<img width="1792" alt="Screenshot 2020-09-09 at 13 35 31" src="https://user-images.githubusercontent.com/3928502/92593486-797b4680-f2a1-11ea-9cc5-aa04d55f440f.png">
Scenario B
<img width="1792" alt="Screenshot 2020-09-09 at 13 35 31" src="https://user-images.githubusercontent.com/3928502/92593576-9fa0e680-f2a1-11ea-83d0-ee92f13f8b89.png">


We need to validate this one together so we can produce a video. As it is I consider it as final unless I get "doable" request

**Comment by LAAP** [comment]
@agrignard ,

I think this scenario **is not working**. I think **we shouldn't show this** as it is now

As I have commented several times and as you can read in the articles that I have shared **NORMAL Air conditioning** (like the one that most buildings have) **can be much worse spreading the virus that Natural ventilation.** Actually, that is the issue in Cafeterias and Bars that are closed indoor spaces. 

With that in Mind, The scenario of Natural ventilation should be better than the Air conditioning one.

**Comment by agrignard** [comment]
Yep your right, it has been fixed in https://github.com/CityScope/CS_Proxymix/commit/c2772f0d4e8b422217c181b88382e8f39beeb9af (so basically a ventilated room now is a room with natural ventilation)

**Comment by LAAP** [comment]
Awesome @agrignard! Thank you!

**Comment by LAAP** [comment]
From the videos sent by @agrignard:

- **Episode2_A:** NATURAL VENTILATION should be the option "B". Here, in the top of natural ventilation we have to add the following measures:
-Time inside of the room needs to be just 45 min (instead of 3h)
-Everyone should have a mask, 
-The density needs to be reduce to 50% (from 35 students to 17students)
-Everyone should keep the 1 or 2m physical distance (or/and lines)
- **Episode2_B:** AC VENTILATION should be the option "A". This video is cool, only few changes are needed: People get infected very quickly, can we have less "initial infected people" in the room (now we have 10 out of 35, that is almost 30% of the population already being infected). Maybe we can reduce them into 3 or 5 "initial infected people", and see the slow evolution of the risk during the 3h. What do you think?

**Comment by agrignard** [comment]
OK the change have been made let's see how it looks

**Comment by LAAP** [comment]
Awesome @agrignard ,

WTB, This is the latest in COVID and ventilation:

https://www.medrxiv.org/content/10.1101/2020.02.28.20029272v2

"The odds that a primary case transmitted COVID-19 in a closed
environment was 18.7 times greater compared to an open-air environment
(95% confidence interval [CI]: 6.0, 57.9). Conclusions: It is
plausible that closed environments contribute to secondary
transmission of COVID-19 and promote superspreading events. Our
findings are also consistent with the declining incidence of COVID-19
cases in China, as gathering in closed environments was prohibited in
the wake of the rapid spread of the disease."

**Comment by agrignard** [comment]
I consider this Episode done. Feel to reopen a specific issue if needed

**Comment by LAAP** [comment]
@agrignard , Can you share a video of the final Episode 2 before closing this Episode?

**Comment by agrignard** [comment]
You can also simply run the model from your computer ;-)

**Comment by agrignard** [comment]
As we are now starting the validation process of this model and that the final video has been released I consider these Episode issues as closed. Please feel free to reopen it or to create more specific issue related to the model itself not to the Video

**Comment by LAAP** [comment]
Hi @agrignard , does this means that we will have not "outdoor-path-following" model?

**Comment by agrignard** [comment]
"outdoor-path-following" model?? This is not related to this Episode isn't it?

**Comment by LAAP** [comment]
Ah! Sorry! I don't know why I was looking in to the issue of the last episode, but my comment finished here, hahahah!

**Comment by LAAP** [comment]
@agrignard I think you can start shooting in a lower level, what about here?: 

Questions about the spec? imdfquestions@apple.com

**Comment by agrignard** [comment]
For the dedicated path of course it needs to be implemented but I want to move a bit forward the exercice of the 5 Episode and having something closer to a ToolKit easy to replciate to other cases

**Comment by LAAP** [comment]
That sounds great! Let's do it!
