### ISSUE TITLE
Episode 3: Sanitation points and social distancing - air conditioning (CUAAD)

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Proxymix#109]
Site: **UDG/CUAAD** 
**2 sub episode**: Difference between people keeping social distancing and using the sanitation points and cleaning the droplets or not.

Density Scenario: people are place with a distance of **2 meter** (if we have the real desk that could be possible to run it)

Code to run (and edit) in **StoryTelling.gaml**

``````
experiment Episode3 type: gui parent: Coronaizer{
	parameter 'fileName:' var: useCase category: 'file' <- "UDG/CUAAD";
	parameter "Density Scenario" var: density_scenario category:'Initialization'  <- "distance" among: ["data", "distance", "num_people_building", "num_people_room"];
	parameter 'distance people:' var: distance_people category:'Visualization' min:0.0 max:5.0#m <- 2.0#m;	
}
``````

This is how it look so far 
<img width="615" alt="Screenshot 2020-08-24 at 12 41 15" src="https://user-images.githubusercontent.com/3928502/91036143-2057b580-e607-11ea-8aa6-e387856e04f4.png">

**Comment by LAAP** [comment]
Hi @agrignard , some small clarifications:

**2 sub episode:** 

_Pre-COVID19_ = No Mask (big sprawl) not following distancing and hygienic rules, and 
_COVID19_ = mask (lower sprawl) and following the rules

Density Scenarios:

_Pre-COVID19_ = @gamalielpalomo and @milkmonica , how many people uses this floor in a normal day?
_COVID19_ = people are place with a distance of **2 meter**, etc

The rest as you have it above

**Comment by agrignard** [comment]
We wil need to add the sanitation point in this dxf if we want to have people going there. @LAAP , @gamalielpalomo , @milkmonica  is is somethign doable for you?

**Comment by LAAP** [comment]
Hi @agrignard ,  @gamalielpalomo, and @milkmonica,

I think that this is a great idea. We should have sanitation points in:
- Toilets
- Access to buildings and Campus
- In front of elevators and/or stairs

And good to have:
- In the access to each classroom, labs, and indoor spaces in general

 @gamalielpalomo , @milkmonica,
I think we could make a new layer in the dxf, where the sanitation points are expressed as a small circle or square

@agrignard ,
Can we have "code" a slider between 0 to 100% for agents using or not the sanitation points?

**Comment by agrignard** [comment]
Hi everyone, it's getting pretty urgent to have the sanitation point at least in this dxf if we want to implement the behavior requested in #121

**Comment by LAAP** [comment]
Hi @gamalielpalomo , @milkmonica ,

Please, can you confirm that this is under control? Please, let me know!

**Comment by milkmonica** [comment]
Hi Luis and Arnaud!
Today, Gama and I are giving a final review to all the issues, since yesterday we had already made all the changes that appeared here.
I imagine that when you work on this specific simulation you will tell us if with the last pull that Gama did, everything was solved.

**Comment by LAAP** [comment]
Awesome @milkmonica and @gamalielpalomo ,
Please, keep closing issues as soon as you solve them! Also, we will open new issues if something is needed  ;)

**Comment by ptaillandier** [comment]
I added in the model the possibility for agent to wash their hands before and after the activity. I am not closing this issue yet because the link with the epidemiological model is still missing.

**Comment by agrignard** [comment]
Great @ptaillandier !! Right now it's a bit hard to see the effect in the Episode 3 but I guess it's because the simulation is too fast

**Comment by agrignard** [comment]
@gamalielpalomo and @milkmonica now that most of the feature are finally here and all the dxf are all ready  can you start to propose some content for this Episode? Let me know if you have any trouble to produce video with GAMA

**Comment by LAAP** [comment]
@agrignard ,

This episode is to see how, in this office building from the UDG, the use of masks, lower density, and sanitation points can help to reduce the infection. Please, notice that the office has AC when the classrooms and Labs has Natural ventilation.

Like in the other episodes; @gamalielpalomo and @milkmonica, please let us know where are the UDG protocols for office and cleaning hands and surfaces. As an example, at MIT you have to clean your hands always when entering and leaving the building, after using closed spaces and toilets, etc. Also, you have to clean your table and equipment before and after using it.

**Comment by agrignard** [comment]
Update on the 09/09/20

Here is what we have it migth be better ones #149 is solved to really see the effect of sanitation when student leave the room

<img width="1792" alt="Screenshot 2020-09-09 at 14 18 41" src="https://user-images.githubusercontent.com/3928502/92597324-86029d80-f2a7-11ea-829a-ca60dc938e14.png">
<img width="1792" alt="Screenshot 2020-09-09 at 14 18 58" src="https://user-images.githubusercontent.com/3928502/92597332-89962480-f2a7-11ea-8d63-0a86295b2388.png">

**Comment by LAAP** [comment]
@agrignard ,

This is great! 

I think that in the case of the library, we **should run a couple of simulations in order to give to the UDG an estimated number of  students using the space** in a safer way as possible. For instance: Pre COVID 250 students where using the library. In a Pandemic scenario, and If all the students clean the hands, where masks, and keep 2m distance, then we test with reductions of 20%, 45%, 50% of the student's using the library, and we pick the best scenario for UDG

**Comment by LAAP** [comment]
From the videos sent by @agrignard:

- **Episode3_A:** This video could be final. Maybe we could have some very small random movement of people going to the toilet on shifting tables (spending 3h without movement in an office is not super realistic, however is making the point), but if we have no time for this small changes, we can keep this video as it is

- **Episode3_B:** (there is a typo in the title) This episode shows the use of sanitation points, as an extra measure of the rest of CDC recommendations, so people should be less infected. However, people get equally infected (or even more) as in the scenario3_A. With that in mind, in this scenario we have to add the following measures:
-Time inside of the room needs to be just 45 min (instead of 3h)
-Everyone should have a mask, 
-The density needs to be reduce to 50% (from 137 students to 68 students)
-Everyone should keep the 2m physical distance all the time (or/and the lines): When people leaves the place the aglomerate a bit

**Also, I have noticed that when people are waiting to use the "cleaning station" they do not follow the physical distance, no line either, so they get more infected on the way out.**

**Comment by agrignard** [comment]
Chnage are made and this issue is reopned https://github.com/CityScope/CS_Proxymix/issues/129

**Comment by agrignard** [comment]
I consider this Episode done in term of implementation. Feel to reopen a specific issue if needed. 
#129 is still open

**Comment by LAAP** [comment]
@agrignard , Can you share a video of the final Episode 3 before closing this Episode?

**Comment by agrignard** [comment]
As we are now starting the validation process of this model and that the final video has been released I consider these Episode issues as closed. Please feel free to reopen it or to create more specific issue related to the model itself not to the Video
