### ISSUE TITLE
Episode 4: Use of common areas (natural ventilation or AC) Lines and masks in common areas - (CUCEA)

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Proxymix#110]
Site: **UDG/CUCEA** WE DON'T HAVE IT SO FAR 

**Episode**: Same than Classroom and Lab, but with a line waiting and a bigger room (library or Restaurant/cafeteria).

Density Scenario: people are place with a distance of **2 meter** (if we have the real desk that could be possible to run it)

Code to run (and edit) in ````StoryTelling.gaml`````

``````
experiment Episode4 type: gui parent: Coronaizer{
	parameter 'fileName:' var: useCase category: 'file' <- "UDG/CUCEA";
	parameter "Density Scenario" var: density_scenario category:'Initialization'  <- "distance" among: ["data", "distance", "num_people_building", "num_people_room"];
	parameter 'distance people:' var: distance_people category:'Visualization' min:0.0 max:5.0#m <- 2.0#m;
}
``````

CANNOT DISPLAY IMAGE AS WE DON'T HAVE THE SITE

**Comment by LAAP** [comment]
Hi @agrignard , some small clarifications:

**2 sub episode:** 

_Pre-COVID19_ = No Mask (big sprawl) no line, and 
_COVID19_ = mask (lower sprawl) and line

Density Scenarios:

_Pre-COVID19_ = as many people as we can fit keeping no distance
_COVID19_ = people are place with a distance of **2 meter** (if we have the real desk that could be possible to run it)

The rest as you have it above

**Comment by agrignard** [comment]
OK thanks to #112 it is now working this is what we have so far 

<img width="1051" alt="Screenshot 2020-08-26 at 14 22 41" src="https://user-images.githubusercontent.com/3928502/91303072-c2160880-e7a7-11ea-864a-5a2d1ddf1286.png">

**Comment by agrignard** [comment]
We need to have the layer for common area (e.g Libray, cafeterie, etc) in the dxf if we want to implement this episode .

@LAAP , @gamalielpalomo , @milkmonica doable?

**Comment by LAAP** [comment]
@agrignard,  @gamalielpalomo and @milkmonica,

Maybe it is more about using this entire floor plan, but identifying (with a label or a different color and a legend) where is the common space, so we can see the general behaviour in and out of the common space. I think that it is the Triangular one, isn't it?:

<img width="430" alt="Captura de pantalla 2020-08-26 a las 15 00 32" src="https://user-images.githubusercontent.com/19315213/91345183-f93ae880-e7ac-11ea-81df-508dc4418288.png">

**Comment by milkmonica** [comment]
Ok, I'm going to make the changes with the dxf. But I have a question: do I only identify these spaces in a generic way as "common space"? I mean regardless of whether it is a library or an auditorium ... or in any case if I put each one in reality is: "library", "terrace", "auditorium", etc.
In fact, I tell you that in this .DFX (and this is also how Gama and I solved the CUT problem) the areas where we want agents to appear do not have the name that corresponds to them, they are simply called "offices", because in range they do not work otherwise, the agents simply do not arrive .

**Comment by milkmonica** [comment]
I can't do the pull request, but I don't want to stop you. I made the changes and shared the drive folder where the file (https://drive.google.com/drive/u/1/folders/1qDCtFPs7N90VdfIRoTMJn-NXnz14XY2m) is. As soon as Gama is available we upload it to GIthub

**Comment by agrignard** [comment]
Hi @milkmonica you have the same permission of @gamalielpalomo in the github so you should be able to PR, let me know if there is any problem. I think this dxf file is the one that @gamalielpalomo PRed here https://github.com/CityScope/CS_Proxymix/pull/123 right?

**Comment by milkmonica** [comment]
I imagine this issue remains open until the video production. 
As Gama has commented, yesterday we made the change of the chairs as well, and let you know that we are pending Github, so that in case any change is needed, you know that we will do it as soon as possibl. Above all, remember our difference of time, so any of you does not have to redo something that we were already doing.

**Comment by LAAP** [comment]
Hi @agrignard ,
For colors I suggest a first try with:

- The yellow room shift into greyish/blueish = rgb (84,102,159)
- The red tables shift into greyish/brownish/greenish = rgb (128,121,72)

Let's see how it looks like

**Comment by agrignard** [comment]
@gamalielpalomo and @milkmonica now that most of the feature are finally here and all the dxf are all ready  can you start to propose some content for this Episode? Let me know if you have any trouble to produce video with GAMA

**Comment by LAAP** [comment]
Hi @agrignard ,

Here the idea is to see how people should follow the rules when using a big common space like a library. Please, notice that the library has AC.

@gamalielpalomo and @milkmonica, please, like in previous episodes, let us know how many people are using the library today and the expected reduction of density of people (maybe it is 50% like in classrooms), physical distance, health measures, and the special measures planed in the protocols of the UDG, so we can simulate it.

**Comment by agrignard** [comment]
Update on 09/09/20. WIP in progess (see #130 )
<img width="1792" alt="Screenshot 2020-09-09 at 14 32 44" src="https://user-images.githubusercontent.com/3928502/92598649-610f2a00-f2a9-11ea-83f5-81801adb8a4c.png">


<img width="1792" alt="Screenshot 2020-09-09 at 14 32 37" src="https://user-images.githubusercontent.com/3928502/92598627-5c4a7600-f2a9-11ea-9029-78f1b03b9fce.png">

**Comment by LAAP** [comment]
Hi @agrignard ,

In this episode, I think that we have to do the same than in the office building and, we should run a couple of simulations in order to give to the UDG an estimated number of students using the space in a safer way as possible. For instance: Pre COVID 228 students (@gamalielpalomo and @milkmonica is this the real number???) were using the Library. In a Pandemic scenario, and If all the students clean the hands, where masks, and keep 2m distance, then we test with reductions of 20%, 45%, 50% of the students using the library, and we pick the best scenario for UDG

**Comment by LAAP** [comment]
From the videos sent by @agrignard:

- **Episode4_A:** This video could also be a final one. I love the Agents moving randomly in the library. There are 2 things:
1) Some spaces don't work with the infection: The people at the spaces outside of the library (Theater, rooms, etc) don't get infected, and the space doesn't  change color into a red scale, looks like the simulation doesn't work out there. I think we should have this spaces working
2) Time inside of the room is 1h (instead of 3h)

- **Episode4_B:** Same; this video can be a final one. In this one, the  spaces outside of the library (Theater, rooms, etc) are working. Interesting. People are using masks, however some measures are not being implemented:
-Time inside of the room needs to be just 45 min (instead of 1h)
-The density needs to be reduced to 50% (from 228 students to 114 students, and now you have 53... we have a lot of infections for that low density )
-Everyone should keep the 2m physical distance all the time (or/and the lines): When people leaves the place the aglomerate a bit

**Comment by agrignard** [comment]
Ok change made and #154 has been created

**Comment by LAAP** [comment]
Awesome!

**Comment by agrignard** [comment]
I consider this Episode done. Feel to reopen a specific issue if needed. #160 is still open to make it even better

**Comment by LAAP** [comment]
@agrignard , Can you share a video of the final Episode 4 before closing this Episode?

**Comment by agrignard** [comment]
As we are now starting the validation process of this model and that the final video has been released I consider these Episode issues as closed. Please feel free to reopen it or to create more specific issue related to the model itself not to the Video
