### ISSUE TITLE
Legend for the video

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Proxymix#114]
@LAAP and Markus please give me your feedback about what we want to display and how.

here is the current version of the text layout. Please tell me what to add or remove

<img width="1792" alt="Screenshot 2020-08-24 at 18 22 58" src="https://user-images.githubusercontent.com/3928502/91070727-72b0ca80-e637-11ea-8002-579b93ca17fd.png">

**Comment by LAAP** [comment]
Hi @agrignard ,

M wishes list is:

**SITE** = OK

**CHARACTERISTICS** = some typos and clarifications:

- **Fiscal** distance [the "Fisical" is important]
- Surface [of what? Tables, floor...? If is floor, then it shouldn't be "surface", we should say "area", ]

**PARAMETERS** = Explain a bit:

- Mask ratio: 1.0 [can we add a %? As an example 1.0 = 100%]

**PROJECTION** = Explain a bit more the meaning:

- Infected new comets: [what is the meaning of this output/parameter? What means "10"? Is 10 a % or a number?]
- Low and high risk... [are this numbers a number of people, a %, a ratio....?]
_____

**CAN WE ADD?:**

- Graphic Leyend: explaining white dots, red circles, 
infected agents, etc....
- Type of ventilation: natural, AC, etc. Number of renovations (if possible)
- Time = Time spent in the classroom, Lab, etc.
- Shifts = Pre-CoVID : 1 shift 3h, vs CoVID: 3 shifts of 45min
- Real time Cake: with low risk vs high risk %
- Fever graph: with the evolution of the high risk cases
- High risk infected area: m2

**Comment by agrignard** [comment]
OK  I will implement this and let you know how it look.

**Comment by agrignard** [comment]
Version fo today taking some of @LAAP input
<img width="1616" alt="Screenshot 2020-08-25 at 15 52 35" src="https://user-images.githubusercontent.com/3928502/91182919-1a3b0500-e6eb-11ea-8857-3a1555c9bbe6.png">

Still to be done but I need more info

_Shifts = Pre-CoVID : 1 shift 3h, vs CoVID: 3 shifts of 45min => I need those value for each Episode
Real time Cake: with low risk vs high risk % => We already have the number of Hight and Low but why not having a pie
Fever graph: with the evolution of the high risk cases => what do you mean by "fever graph"? 
High risk infected area: m2_ => not sure if it makes sense how to you established that an area in high risk? Number of infection  that has been occuring here?

**Comment by LAAP** [comment]
Hi @agrignard ,

This is great! Thanks! 

---
**Suggestions:**

**1) Low Risk Vs high Risk** = Can we have a "gradient"? Having a 2nd level of "Medium risk" in orange color? 

**2) Access to building** = Now is red color, can we change it into blueish color? something like rgb(0, 169, 217)? 

---- 
**My answer:**

_- Shifts = Pre-CoVID : 1 shift 3h, vs CoVID: 3 shifts of 45min => I need those value for each Episode_ 

(I think this value should came from the simulation, however, if not possible, I ca use the IDSS graph, as I did in the first Presentation back in July)

_- Real time Cake: with low risk vs high risk % => We already have the number of High and Low but why not having a pie_ 

(It could be cool to have a dynamic visual way to show it. The Pie can show, in real time, just with colors, how "High risk infected people are growing depending on how people follow the rules or not. The Pie could have the green (low), orange/yellow (medium), and red (high) colors, changing in parallel with the numbers: Visual inputs are usually easier to understand than numbers by students and citizens)

- Fever graph: with the evolution of the high risk cases => what do you mean by "fever graph"?

(I mean, to have a "fever chart" or "time-series charts" like the one that we made at the city level showing infections and deaths, but showing the evolution of the risk level: 

"A fever chart is a graphical representation showing change of a variable over time.
Fever charts are used for data that changes continuously, like stock prices. They allow for a clear visual representation of a change in one variable over a set amount of time. Fever charts are sometimes called time-series charts. 
https://whatis.techtarget.com/definition/fever-chart")

- High risk infected area: m2 => not sure if it makes sense how to you established that an area in high risk? Number of infection that has been occuring here? 

(I think that it is easier to measure by time spent in a room by an infected person vs air renovations (ventilation)) Since the simulation probably doesn't have yet the ventilation level, etc. Maybe is number of cases per m2 of room

**Comment by agrignard** [comment]
1) Low Risk Vs high Risk = Can we have a "gradient"? Having a 2nd level of "Medium risk" in orange color?
=> hard to do as people are either S or I (there is no real intermediate states)

2) Access to building = Now is red color, can we change it into blueish color? something like rgb(0, 169, 217)?
done

<img width="902" alt="Screenshot 2020-08-26 at 14 27 30" src="https://user-images.githubusercontent.com/3928502/91303419-4cf70300-e7a8-11ea-8aef-0b2df5788738.png">

---------------------------------------

- Shifts = Pre-CoVID : 1 shift 3h, vs CoVID: 3 shifts of 45min => I need those value for each Episode

(I think this value should came from the simulation, however, if not possible, I ca use the IDSS graph, as I did in the first Presentation back in July)
=> So this will just impact on the time spent right? there is a dedicated issue for that https://github.com/CityScope/CS_Proxymix/issues/117 to be able to specify it in the simulation as a parameter, let's see if we can implement it
---------------------------------------

- Real time Cake: => see https://github.com/CityScope/CS_Proxymix/issues/118


-  Fever chart => https://github.com/CityScope/CS_Proxymix/issues/119 (already tehre but in a separated window for now)

- High risk infected area => https://github.com/CityScope/CS_Proxymix/issues/120

**Comment by LAAP** [comment]
Hi @agrignard,

My answer:

- Low Risk Vs high Risk = Can we have a "gradient"? Having a 2nd level of "Medium risk" in orange color?
=> hard to do as people are either S or I (there is no real intermediate states)

How and when people shift from "S" to "I" ? I am sure that there is a "process of agents contamination", actually, in the real world you get infected when your "viral load" gets high. Can we have something like that? Something like "S", "M", "I" ?

**Comment by agrignard** [comment]
With the new infection method implemented by @ptaillandier we now have low, medium and risj where the threshodl is a parameter between 0 and 1 (e.g below 03 is low, between 0.3 and 0.6 is medium and high than 0.6 is high)
 
`````
float Low_Risk_of_Infection_threshold<-0.3;
float Medium_Risk_of_Infection_threshold<-0.6;
`````

<img width="375" alt="Screenshot 2020-09-08 at 13 39 41" src="https://user-images.githubusercontent.com/3928502/92472038-36ee3700-f1d9-11ea-9c29-27a1e8cf5ebb.png">


I close this issue as the legend video has been validated by our world class designer @MagnusTheGreat a.k.a @MarkusElKatsha that we still cannot tag in an issue (

**Comment by LAAP** [comment]
Fantastic job guys! @ptaillandier and @agrignard , thank you for this new push!
