### ISSUE TITLE
THE  CURRENT FATHER CHRISTMAS LIST

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Proxymix#121]
A big thanks to @ptaillandier that is back from vacation and is willign to help us on the final lap.

I have been discussing with him and he will implement a way to define specific scenario for each episode, instead of having always the same model which is now a DailyRoutine where people enter, go to work, go to lunch, go back to work etc.

As in most of the Episode we just want to show how peopel enter and exit the space the scenario will be much more simple but @ptaillandier proposed to give the possibility to define more complex one.

So here is a first draft scenario description for each Episode based on my understandign of what we want to show but @LAAP feel free to modify it

So by default peopel will just enter to classrooms and go back then we might have different one

- Episode 1: 
People enter form the Entrance, go to Classrooms (not office?) stay for N min (N being define as timeSpent)

- Episode 2
People enter form the Entrance, go to Classrooms (not office?) stay for N min (N being define as timeSpent)

- Episode 3
People enter form the Entrance, go to Sanitation point, then go to Classrooms stay for N min (N being define as timeSpent), and then why not some of them goes time to time to Sanitation point? However what is the effect of the saniation point? We never implemented that... maybe if people go there being infected then they become recoverd? Doesn't sound very realistic but it can tell the story

- Episode 4
People enter and goes to Common Area (maybe just wander there instead of staying on the desk)

- Episode 5
I am not sure yet how will be this episode as I don't know how look the dxf (see #111) but for now let's have the classic entrance + classrooms but then we need to specify (first to build it) a different pedestiran path (this coudl be also a parameter)

@LAAP this is some precook scenario to help @ptaillandier to implement it but it can be modify/discuss (not too much though ;-) )

**Comment by LAAP** [comment]
Hi @ptaillandier , 

Thank you so much for your help! Let me add some info to @agrignard scenarios and ideas:

The goal of the simulation is to show how if we behave as the old "Normal", we will be potentially infected, so we need to follow the rules in order to reduce the potential level of infection. 

**A) Scenarios:** 
Keeping this in mind, in **each episode** we want to show 2 simulations/scenarios: 

- **Scenario-1. People behaving in a pre-COVID way, but in a era of pandemics:** so a lot of people gets "potentially infected". This means that, we have to show how a lot of people gets in "real time" from "non infected" to "potentially infected" (for instance: they shift from "white or green" color, to "orange color if they are augmenting their risk, and finally to "red color with an outer red circle") because dey do not follow the rules.

- **Scenario-2. People behaves following the CDC rules for safety and security:** here we want to show how, if you follow the rules, some people can get  "potentially infected", but only few and "controlled" ones.

**B) General behaviour of the agents:**
The general behaviour is:

- Step-1: Agents accessing to the places (Campus, Buildings, rooms, stairs...), in Scenario-1 people do not make lines and in Scenario-2 people make lines and keeps the distance, etc.
- Step-2: Agents staying in these different place different time depending on the activity. In Scenario-1 timing as it just to be (example, a class is 3h), in scenario-2 shorter timing with shifts (example 3 shifts of 45 min in classrooms, and cleaning after each shift)
- Step-3: Agents following or not the rules: in Scenario-1 people do noting special and gets "potentially infected", but in Scenario-2 people follows the rules and are a bit safer (example: Using the sanitation points, making lines, keeping social distancing, cleaning the working space and tables, shifts of people, cleaning teams after shifts, one direction paths, etc.)
- Step-4:  Agents finishing activity and going to the next one or going back "home". Similar to Step-1.

**C) Episodes:**
Let me add some more info to @agrignard Episodes:

- **Episode 1:**
We want to show how people can get infected if they do not follow the rules when using a classroom:

**Scenario-1.** People enter form the Entrance, go to Classrooms (and to all the indoor spaces of the building: The zoom can be in a classroom level, but if we have the dxf of the entire building, it will be cooler if we show the behaviour in the entire building) and they follow steps 1 to 4, defined below: stay for N min (N being define as timeSpent) in the classroom, N' min Lab, N'' min office, N''' min Library....... And we show how they "potentially get infected", and then they shift from rooms and/or go back home 

**Scenario-2:** Same, but, as explained below in point A, and B, with people following the rules and with less infection risk

- **Episode 2:**
We want to show how people can get infected if they do not follow the rules when using a Lab:

**Scenario-1.** People enter form the Entrance, go to Labs (and to all the indoor spaces of the building: The zoom can be in a Lab level, but if we have the dxf of the entire building, it will be cooler if we show the behaviour in the entire building) and they follow steps 1 to 4, defined below: stay for N min (N being define as timeSpent)... etc, etc, etc.  and at the end people gets "potentially infected"

**Scenario-2:** Same, but, as explained below in point A, and B, with people following the rules and with less infection risk

- **Episode 3:**
We want to show how people can get infected if they do not use the sanitation points:

**Scenario-1.** People enter form the Entrance, go to their working place (office, Labs, classrooms...) and they follow steps 1 to 4, defined below: stay for N min (N being define as timeSpent)... etc, etc, etc.  and at the end people gets "potentially infected"

**Scenario-2.** People enter form the Entrance, go to Sanitation point, then go to all the working spaces (office, Labs, classrooms...) and they follow steps 1 to 4, defined below: stay for N min (N being define as timeSpent), and then why not some of them goes time to time to Sanitation point? However what is the effect of the saniation point? We never implemented that... maybe if people go there being "potentially infected" then they "reduce" their "infection level" and became "less infected" (@agrignard , this is the reason why, a gradient between green, orange and red for showing the infection could be cool), and maybe only "orange people" can be "recovered", but red people not? Doesn't sound very realistic but it can tell the story... Open to you guys. Also could be just related to the droplets, As I have mentioned in a previous issues. Maybe what you clean are the droplets, so you reduce the level of infection.


- **Episode 4:**
We want to show how people can get infected if they do not follow the rules when using a common area coffee or library or similar:

**Scenario-1.** People enter and goes to Common Area (some of them wander there and some of them stays on the desks) and they follow steps 1 to 4, defined below: stay for N min (N being define as timeSpent)... etc, etc, etc.  and at the end people gets "potentially infected"

**Scenario-2:** As explained below in point A, and B, with people following the rules and with less infection risk

- **Episode 5:**
We want to show how people can get infected if they do not follow the rules when using the access and the paths in the entire campus:

Similar to the visualization that @agrignard did the first time at the campus level. We want to show how people access to the campus and moves in the campus

**Scenario-1.**: people access in pick time to the campus, not makes lines, no sanitation points, no distancing, no masks, no nothing, the move "like fishes" into the different buildings, (follows steps 1 to 4 above), they get "potentially infected" in a very high rate.

**Scenario-2:** As explained below in point A, and B, with people following the rules: making lines, for accessing to campus and buildings, physical distancing, paths, masks, sanitation points, etc. So people gets less infection risk

Please, let me know if something is unclear

**Comment by ptaillandier** [comment]
Very interesting, but that's a lot to do :) 

In terms of works, what's the priority. I mean are there any simulations that you need to run in priority (to start producing videos, graphics or whatever you want).

By simulation, I mean here :
- a dxf
- behavior for agents (agenda, type of behavior in relation to the Covid, etc.)
- possibly a rule for the placement of workstations.

**Comment by agrignard** [comment]
Hi @ptaillandier thank you for your input and of course I totally agree with you that it's a tremendous whishlist especially with the few amount of people working on it on the time we have . So no pressure for you especially as you are an external voluntary collaborator. This is the Christmas list from @LAAP  and it might be completed actually for Christmas ;-) 

More seriously, as discussed with the team and looking and all the requirement and the delay that has been taken to produce the files and the fact that we didn't find enough programmer to help us the priority will be to deliver Episode by Episode and it would be great to have the first one before the 1st of September and then we will deliver Episode by Episode doing the maximum we can with the ressources we have.

I will reconsolidate and ventilate on each specific issue Episode by Episode the "@LAAP christmas list".

**Comment by agrignard** [comment]
@LAAP two things are not clear for me and different from waht we agree in this episode

_Scenario-1. People enter form the Entrance, go to Classrooms (and to all the indoor spaces of the building: The zoom can be in a classroom level, but if we have the dxf of the entire building, it will be cooler if we show the behaviour in the entire building) and they follow steps 1 to 4, defined below: stay for N min (N being define as timeSpent) in the classroom, N' min Lab, N'' min office, N''' min Library....... And we show how they "potentially get infected", and then they shift from rooms and/or go back home_

1. "and to all the indoor spaces of the building"=> we need to agree where do they go, right now they go in classrooms and that's all, the rest is meeting rooms in this case. So WE NEED TO AGREE ON THIS

2. "stay for N min (N being define as timeSpent) in the classroom, N' min Lab, N'' min office, N''' min Library......."=> again this is doable but we need to agree also! I though we were just showing the shift of the student no????

**Comment by agrignard** [comment]
Ok so this crazy christmas list issue has made some baby which are so far

#124 => Gama people 
#125 => Gama people almost done
#126 => AutoCad people
#127 => Gama people
#128 => Gama people
#129 => Gama peopel but we need 
#130 => Gama people but cannot be done until #131 is done
#131 => Autocad people

And of course still

#107, #108, #109, #110, and #111 are the one we want to close at the end

**Comment by LAAP** [comment]
Dear @ptaillandier , 

Thank you very much for all the help and support that you are providing to us. You are fantastic!!!

Hi @agrignard ,

Thanks for your questions about Episode-1. I think that we need to be "creative and strategic" here, and depends on how far is the simulation ready for showing the different behaviours. 

With that in mind, we have two "zoom/scale" options:

**A) Closer scale/zoom** = If we only have student's behaviour, then, we only do "classrooms level": In the video we only zoom in to the classroom level:

<img width="298" alt="Captura de pantalla 2020-08-27 a las 10 35 14" src="https://user-images.githubusercontent.com/19315213/91456466-4ff9fe00-e851-11ea-982d-6f94658e47f9.png">

**B) Building level** = If we can show people going to the classroom, office, Labs, etc. : Then in the video we show the entire floor of the building:

<img width="589" alt="Captura de pantalla 2020-08-27 a las 10 35 22" src="https://user-images.githubusercontent.com/19315213/91456710-98192080-e851-11ea-91f5-2d7c18d61d6e.png">

**Comment by agrignard** [comment]
I see all the desk on this screenshot, is it an Autocad or a pdf? couldn't it be used for #126????

**Comment by LAAP** [comment]
@agrignard , 

Answering also your questions more specifically: 

I think you have been in the same meetings than me, and that you know that we are trying to show a "realistic behaviour of the people". **The goal is to show that, if people keeps their normal daily routine will get potentially infected, so they have to follow CDC rules**. That is the reason why we asked about the "normal" behaviour of people in building  "O" (that can be extrapolated to the rest of UdeG campuses and buildings). You can find the excel from UdeG here: 

https://drive.google.com/file/d/11z3WEC7OxjSrwTkV6uJK1mY_jE3YljtV/view?usp=sharing

**The scenario 1**, should be with students, staff etc. always following this "normal behavior" and see how they get potentially infected

**The scenario 2**, should be with people following CDC rules: masks, paths, lines, cleaning, and less time inside of indoor rooms, and see how the infection level is lower.

- "and to all the indoor spaces of the building"=> we need to agree where do they go, right now they go in classrooms and that's all, the rest is meeting rooms in this case.

We should try to have a behaviour as realistic as possible. If we can't have all the diversity of agents, we should focus in one type of agent per episode

- "stay for N min (N being define as timeSpent) in the classroom, N' min Lab, N'' min office, N''' min Library......."=> again this is doable but we need to agree also! I though we were just showing the shift of the student no????

I think this was clear; As I have explained above, scenario 1 = normal behaviour, no shifts, students from 07:00-22:00 HRS in class, changing every 3h (see excel). Scenario 2 = shifts every 45min (if we can't calculate it from the simulation, 45 min will be the max time in the classroom following IDSS data)

**Comment by LAAP** [comment]
> I see all the desk on this screenshot, is it an Autocad or a pdf? couldn't it be used for #126????

Hi @agrignard ,

We have a cad file, dxf and pdf file of module "o" with furniture in the google drive, since June 29th:

https://drive.google.com/drive/folders/1_HmN7un2iLySR-rxhJkjCJfKAkwfNsAr?usp=sharing

**Comment by agrignard** [comment]
Most of th Father Christams list are now implemented. So I consider this issue as closed
