### ISSUE TITLE
Produce the desk layout for each dxf

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Proxymix#126]
@gamalielpalomo, @milkmonica , @LAAP or any AUTOCAD expert we need to have the desk layout for the classrooms in most of the Episode. 

Right now there is no layout and people are just equally place in the room, it will looks much more realistic with desks...

Is it something doable?

**Comment by LAAP** [comment]
Dear all; @agrignard , @gamalielpalomo, and @milkmonica

We have a CAD, dxf and pdf file with fourniture in the Google Drive since June 29th:

https://drive.google.com/drive/folders/1_HmN7un2iLySR-rxhJkjCJfKAkwfNsAr?usp=sharing****

Example:

https://drive.google.com/file/d/1DhE4Pok-k5iJ9XM43zB2bjOpMSxd05Ae/view?usp=sharing

<img width="1429" alt="Captura de pantalla 2020-08-27 a las 10 57 42" src="https://user-images.githubusercontent.com/19315213/91459443-a6b50700-e854-11ea-8076-0aac83d72774.png">

**Comment by agrignard** [comment]
So for the first Episode CUT it would be great to have it (I guess it's only a kind of copy paste from originla file to the current building.dxf.

You can have a look at the one in the file ProxymixABM/CityScience/building.dxf the name of the layer should be **"Furniture"** with a capital F and no s

**Comment by LAAP** [comment]
@agrignard ,

Yes, that should be a work of few minutes. @gamalielpalomo and @milkmonica , Do you have this under control? Please, let me know!

**Comment by gamalielpalomo** [comment]
Hi @agrignard, @LAAP,
Furniture layer is in all the dxfs, in the case of CUT/Lab they are work tables at the center of the room.

**Comment by agrignard** [comment]
Ok great peopel are now going to the real desk

<img width="741" alt="Screenshot 2020-08-28 at 21 31 03" src="https://user-images.githubusercontent.com/3928502/91608424-d445a180-e975-11ea-891d-a5f9068ea34f.png">

There is still a kind of weird shape for the room (the gray polygon) is there a way to modify it so it has the real shape of the building?

**Comment by agrignard** [comment]
Can we have it also for CUCS as mention by @LAAP ?

**Comment by agrignard** [comment]
OK we now just need #139 the rest is ok thanks to #140
