### ISSUE TITLE
CUT dxf choice 

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Proxymix#134]
Right now we have 3 sites for CUT
labs, room104 and the whole campus.

So far the Episode 3 #108 is for the mab, do we want ot keep it for the lab? What do we do for room 104 and the hole campus?

**Comment by LAAP** [comment]
Hi @agrignard ,

I think that the correlation of episodes and Buildings (dxf files) was clear since long time ago. 

The real correlation was:

- **Episode 1: CLASSROOM** = **CUCS** = Masks in Classroom with - Natural Ventilation - 

- **Episode 2: LAB** = **CUT** (Lab) = Use of masks scene Lab - air conditioning - 

- **Episode 3: OFFICE** = **CUAAD** = Sanitation points and social distancing - air conditioning - 

- **Episode 4: LIBRARY and/or CAFETERIA** = CUCEA = Use of common areas (natural ventilation or AC) Lines and masks in common areas -

- **Episode 5: CAMPUS** = CUSUR = Social distance, masks and dedicated Paths in an open space - 

With that in mind,  "Episode 3 #108" in **NOT** the **LAB** ist is the **OFFICE** 

Also, **CUT** is **ONLY** the **LAB** (and maybe the building with a lot of LABs and classrooms), but **NOT** the **campus**

**Comment by agrignard** [comment]
Yes I agree but I see 3 different sites for CUT so I had a doubt. Let s see if we use the extra one but we already have more than enough with what we have
