### ISSUE TITLE
Grand Hotel Dieu Covid Invalid DXF

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Proxymix#29]
When running COVID.gaml and choosing ````Grand-Hotel-Dieu_Lyon ````
Right now the Grand Hotel Dieu mode doesn't work on the COVID Simlation;

it seems that the entrances are not created correctly. Which producced an error in the follwoing part of the code (as myself.entrances is null)

`````
point pte <- myself.entrances closest_to self;
dists <- self distance_to pte;
`````

myself.entrances is computed like this 

`````
if contour != nil {
  entrances <- points_on (contour, 2.0);
}
``````

**Comment by agrignard** [comment]
@cocsfav can you check the unit in your file? it seems to me that thjere is somethign wrong with the unit. We are currently using meter

**Comment by cocsfav** [comment]
@agrignard I just checked the unit of the DXF file. It was in a wrong unit. Now it is in meter.
I still have a problem when I try to run the COVID model with the Grand-Hotel-Dieu_Lyon DXF file ; 
![20200518_ERROR_Capture](https://user-images.githubusercontent.com/64479147/82229403-ae4a4300-992a-11ea-965d-a7048026cfd7.JPG)

**Comment by ptaillandier** [comment]
There are three issues with this DXF:
- the unity of the dxf (m instead of cm)
- in Grand-Hotel-Dieu_Lyon, you have the outdoor wall... that should not be considered as a polygon
- sometimes, due to the distance chosen (0.3), there were not entrance to the room.

I committed a fix: 
- the unity is now a parameter (not very nice as you have to define for Lyon "#m" and for the standard dxf "#cm", but better than nothing
- Instead of considering wall overlapping rooms as polygons, I consider them as polylines (not perfect, but, at least it works).
- now smaller distance can be used (loop)

**Comment by agrignard** [comment]
Ok so I was wrong I though it has to be in #m so thank you @ptaillandier for the fix. I ll check that and start to run the ABM on the Grand-Hotel_dieu
