### ISSUE TITLE
COVID RELATED TODOLIST

### ISSUE THREAD

**Issue by agrignard** [CityScope/CS_Proxymix#42]
**Goal:** Develop a tool that people can use to explore scenarios related
to safely opening up workplaces and other facilities where people
gather.

**Score:** It would allow a combination of policies to be scored, probably
using R0 (a target R0 could be established - not sure what that would
be)

**Target Audience:**  Decision makers who control policy - for example,
PIs who manage labs, corporate facility managers, store managers, etc.

Parameters that could be adjusted could include:

- density (limiting people entering a space)
- spacing of workstations, tables, corridor widths, etc.
- separators between stations (yes/no)
- mask policies (maybe all masks, no masks, 50% masks)
- handwashing/sanitizer upon entry  (yes/no)
- temperature check upon entry  (yes/no - prohibiting people with fever)
- ventilation (maybe good/poor)

**Comment by ptaillandier** [comment]
I think you are more insterested in **Re** than in **R0**: https://en.wikipedia.org/wiki/Basic_reproduction_number. **R0** is more an input for me.

Most of the proposed things seem to be very easy to integrate to the model in terms of mechanics (just integrating a factor of decrease in the probability of contagion), but very difficult to quantify (for example, for the wearing of masks, decrease of 75%, 50%, less...).

- density (limiting people entering a space) : What happens when someone wants to enter a room that's already "too crowded"? Will people line up to enter the room? Go somewhere else? 

- spacing of workstations, tables, corridor widths, etc. : for the workstations/tables it should be easy... for the corridor, not sure to understand how you plan to manage that....

- separators between stations (yes/no) : do you have an idea of the impact of that ?

- mask policies (maybe all masks, no masks, 50% masks) : same question, what is the impact of wearing a mask ? It depends on the type of mask and how people use them. 

- handwashing/sanitizer upon entry (yes/no) : It's even more difficult than masks to determine their effectiveness ;) .

- temperature check upon entry (yes/no - prohibiting people with fever) : seems easy to take into account. 

- ventilation (maybe good/poor) : same as for the mask/washing hand, it is difficult to define the real impact of the ventilation.

**Comment by pacopaco74** [comment]
For the following issues we may have to rely on existing research and scientific publications as we seem to lack on data about the effectiveness of such measures ?? : 

- separators between stations (yes/no)
- mask policies (maybe all masks, no masks, 50% masks)
- handwashing/sanitizer upon entry (yes/no)
- temperature check upon entry (yes/no - prohibiting people with fever)
- ventilation (maybe good/poor)

I could give it a look if needed.

**Comment by agrignard** [comment]
Density: See https://github.com/CityScope/CS_Proxymix/issues/47
Workstation: https://github.com/CityScope/CS_Proxymix/issues/48
Separator: https://github.com/CityScope/CS_Proxymix/issues/49
Mask: https://github.com/CityScope/CS_Proxymix/issues/50
Handwashing: https://github.com/CityScope/CS_Proxymix/issues/51
Temperature: https://github.com/CityScope/CS_Proxymix/issues/52
Ventialtion is too difficult to implement for now

**Comment by agrignard** [comment]
All the dedicated issue have been recreated
